artifact_uri: file:///home/runner/work/heartdisease-prediction/heartdisease-prediction/model/model_tracking/0/daffbbf1fd5842d8880e3f632e57f61e/artifacts
end_time: 1654609373394
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: daffbbf1fd5842d8880e3f632e57f61e
run_uuid: daffbbf1fd5842d8880e3f632e57f61e
source_name: ''
source_type: 4
source_version: ''
start_time: 1654609368129
status: 3
tags: []
user_id: runner
