## EDITABLES

tags:
  model_tag: 'BaseLine'
  trained_from: 'Github CI CD'
  model_type: 'Ensemble'

model_parmas:
  n_estimators: 100
  max_depth: 10
  random_state: 32
  oob_score: True
  max_features: 'log2'
  bootstrap: True