## EDITABLES

tags:
  model_tag: 'Tree'
  trained_from: 'Github CI CD'
  model_type: 'Ensemble'
  
model_parmas:
  n_estimators: 23
  max_depth: 12
  random_state: 53
  oob_score: True
  bootstrap: True
  warm_start: True
