## EDITABLES

tags:
  model_tag: 'BaseLine'
  trained_from: 'Github CI CD'
  model_type: 'Ensemble'

model_parmas:
  n_estimators: 300
  max_depth: 100
  random_state: 343
  oob_score: True
  bootstrap: True
