## EDITABLES

tags:
  model_tag: 'Tree'
  trained_from: 'Github CI CD'
  model_type: 'Ensemble'
  
model_parmas:
  n_estimators: 2
  max_depth: 15
  random_state: 555
  oob_score: True
  bootstrap: True
  warm_start: True
