artifact_uri: file:///C:\Users\HP\Desktop\Mlops-Workout\model\model_tracking\0\dc2d84e989af4a4a8072dced56d95d54\artifacts
end_time: 1654672611785
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: dc2d84e989af4a4a8072dced56d95d54
run_uuid: dc2d84e989af4a4a8072dced56d95d54
source_name: ''
source_type: 4
source_version: ''
start_time: 1654672611626
status: 4
tags: []
user_id: HP
