artifact_uri: file:///C:\Users\HP\Desktop\Mlops-Workout\model\model_tracking\0/c04b419bc8fb4058926d8ebf767df8c4/artifacts
end_time: 1654672700435
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c04b419bc8fb4058926d8ebf767df8c4
run_uuid: c04b419bc8fb4058926d8ebf767df8c4
source_name: ''
source_type: 4
source_version: ''
start_time: 1654672687047
status: 3
tags: []
user_id: HP
