artifact_uri: file:///home/runner/work/heartdisease-prediction/heartdisease-prediction/model/model_tracking/0/7473b63a5ac446a7ab10947cbea2d176/artifacts
end_time: 1654594361904
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 7473b63a5ac446a7ab10947cbea2d176
run_uuid: 7473b63a5ac446a7ab10947cbea2d176
source_name: ''
source_type: 4
source_version: ''
start_time: 1654594357942
status: 3
tags: []
user_id: runner
