artifact_uri: file:///home/runner/work/heartdisease-prediction/heartdisease-prediction/model/model_tracking/0/a9b3cbbf40f54146b91121ce964b87d0/artifacts
end_time: 1654613851842
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a9b3cbbf40f54146b91121ce964b87d0
run_uuid: a9b3cbbf40f54146b91121ce964b87d0
source_name: ''
source_type: 4
source_version: ''
start_time: 1654613846483
status: 3
tags: []
user_id: runner
