artifact_uri: file:///C:\Users\HP\Desktop\Mlops-Workout\model\model_tracking/0/df41345623b04e5db0ded78620c597bc/artifacts
end_time: 1654236213235
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: df41345623b04e5db0ded78620c597bc
run_uuid: df41345623b04e5db0ded78620c597bc
source_name: ''
source_type: 4
source_version: ''
start_time: 1654236197953
status: 3
tags: []
user_id: HP
