artifact_uri: C:\Users\HP\Desktop\heartdisease-prediction\model\model_tracking\0\518557b8216d47afba05e86dcdd33502\artifacts
end_time: 1654249540760
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 518557b8216d47afba05e86dcdd33502
run_uuid: 518557b8216d47afba05e86dcdd33502
source_name: ''
source_type: 4
source_version: ''
start_time: 1654249525033
status: 3
tags: []
user_id: HP
