artifact_uri: file:///home/runner/work/heartdisease-prediction/heartdisease-prediction/model/model_tracking/0/9e834ce51f0344ee80e30754407eb12a/artifacts
end_time: 1654608251735
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9e834ce51f0344ee80e30754407eb12a
run_uuid: 9e834ce51f0344ee80e30754407eb12a
source_name: ''
source_type: 4
source_version: ''
start_time: 1654608247605
status: 3
tags: []
user_id: runner
