artifact_uri: file:///home/runner/work/heartdisease-prediction/heartdisease-prediction/model/model_tracking/0/de6a93aa85a74131819865cffbf0db36/artifacts
end_time: 1654616979291
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: de6a93aa85a74131819865cffbf0db36
run_uuid: de6a93aa85a74131819865cffbf0db36
source_name: ''
source_type: 4
source_version: ''
start_time: 1654616975117
status: 3
tags: []
user_id: runner
