artifact_uri: file:///C:\Users\HP\Desktop\Mlops-Workout\model\model_tracking\0/b88bc460cf1444c18e2b11f05e4f2f3b/artifacts
end_time: 1654581297993
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b88bc460cf1444c18e2b11f05e4f2f3b
run_uuid: b88bc460cf1444c18e2b11f05e4f2f3b
source_name: ''
source_type: 4
source_version: ''
start_time: 1654581286381
status: 3
tags: []
user_id: HP
