name: experiments
on: 
  pull_request:
    branches:
      - experiments
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'
      - name: Package Installing
        run: |
          pip install -r requirements.txt
      - name: Downloading Dataset
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          dvc pull Dataset/heartdisease_indicator_test.csv.dvc
          dvc pull Dataset/heartdisease_indicator_train.csv.dvc
      - name: Retrain model
        run: |
          python Models/model/train.py
      - name: "Read Metrics"
        run: |
          OUTPUT=$(cat Models/model/Assests/metrics.md)
          echo 'MESSAGE<<EOF' >> $GITHUB_ENV
          echo  "$OUTPUT"  >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: mshick/add-pr-comment@v1
        with:
          message: ${{ env.MESSAGE }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false
