name: experiments
on: 
  pull_request:
    branches:
      - experiments
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Read Metrics"
        run: |
        
          echo "## Metrics" >> report.md
          METRICS=$(cat Models/model/Assests/metrics.md)
          echo $METRICS >> report.md
          OUTPUT=$(cat report.md)
          
          echo "MESSAGE=$OUTPUT" >> $GITHUB_ENV
          echo 'MESSAGE<<EOF' >> $GITHUB_ENV
          echo  "$OUTPUT"  >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
      - uses: mshick/add-pr-comment@v1
        with:
          message: ${{ env.MESSAGE }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
      # - uses: iterative/setup-cml@v1
      # - uses: actions/setup-python@v2
        # with:
        #   python-version: '3.10.4'
      # - name: Package Installing
      #   run: |
      #     pip install -r requirements.txt
      # - name: Retrain model
      #   run: |
      #     python Models/model/train.py
      # - name: Write CML report
      #   env:
      #     REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     cml send-comment Models/model/Assests/metrics.md
