name: experiments
on: 
  pull_request:
    branches:
      - experiments
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'
      - name: Package Installing
        run: |
          pip install -r requirements.txt
      - name: Downloading Dataset
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          dvc pull dataset/heartdisease_indicator_test.csv.dvc
          dvc pull dataset/heartdisease_indicator_train.csv.dvc
          dvc pull -r models
      - name: Retrain model
        run: |
          python model/train.py
      - name: Making Report
        env:          
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics" > report.md
          cat model/resources/metrics.md >> report.md
          echo $'\n' >> report.md
          echo "## Confusion Matrix" >> report.md
          cml publish model/resources/Confusion-Matrix.png --md >> report.md

          if [[ -f "model/resources/Comparing-Version.png" ]]; then
            echo $'\n' >> report.md
            echo "## Comparing LastVersion" >> report.md
            cml publish model/resources/Comparing-Version.png --md >> report.md
          fi
          
          OUTPUT=$(cat report.md)
          echo 'MESSAGE<<EOF' >> $GITHUB_ENV
          echo  "$OUTPUT"  >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: mshick/add-pr-comment@v1
        with:
          message: ${{ env.MESSAGE }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: True
