name: experiments
on: 
  pull_request:
    branches:
      - experiments
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Read Metrics"
        run: |
          echo "## Metrics" >> report.md
          METRICS=$(cat Models/model/Assests/metrics.md)
          echo $METRICS >> report.md
          echo "## Confustion Matrics" >> report.md
          IMAGE=$( base64 Models/model/Assests/confusion_matrix.png )
          IMAGE_DATA="<img src='data:image/png;base64, ${IMAGE}' />"
          echo $IMAGE_DATA >> report.md
          cat report.md
        
          OUTPUT=$(cat Models/model/Assests/metrics.md)
          echo 'MESSAGE<<EOF' >> $GITHUB_ENV
          echo  "$OUTPUT"  >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
      - uses: mshick/add-pr-comment@v1
        with:
          message: ${{ env.MESSAGE }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false
