name: experiments
on: 
  pull_request:
    branches:
      - experiments
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'
      - name: Package Installing
        run: |
          pip install -r requirements.txt
      - name: Retrain model
        run: |
          python Models/model/train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml send-comment Models/model/Assests/metrics.md
