name: Model-Update-Push

on:
  pull_request:
    types: [closed]
    branches: 
      - experiments

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'
      - name: Package Installing
        run: |
          pip install -r requirements.txt
      - name: Downloading Dataset
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          dvc pull dataset/heartdisease_indicator_test.csv.dvc
          dvc pull dataset/heartdisease_indicator_train.csv.dvc
      - name: Run-Track-Training
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          python app_modules/fix_path.py
          python model/run_track_training.py
      - name: Push-Latest-Model
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          run_id=$(python model/run_track_training.py --run_id True)
          git add model/
          git commit -m "✅Updated Model -> $run_id"
          git push
